### ISSUE TITLE
cwl-metrics with large payload

### ISSUE THREAD

**Issue by kmhernan** [inutano/cwl-metrics#2]
Hello,

Trying to run using a pretty big workflow and get errors like `java.lang.IllegalArgumentException: Limit of total fields [1000] in index [workflow] has been exceeded`

The `cwl_log.json` is like 85kb and it will be bigger when it completes successfully... any thoughts here?

Edit: a bit more info:

```
[2018-07-02T22:20:45,039][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [-govENG] failed to put mappings on indices [[[workflow/KGk8TR1FRPa4JlPn4tc7zA]]], type [workflow_log]
java.lang.IllegalArgumentException: Limit of total fields [1000] in index [workflow] has been exceeded
	at org.elasticsearch.index.mapper.MapperService.checkTotalFieldsLimit(MapperService.java:626) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:450) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:353) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:285) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:313) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [elasticsearch-6.2.2.jar:6.2.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[2018-07-02T22:20:45,053][DEBUG][o.e.a.b.TransportShardBulkAction] [workflow][2] failed to execute bulk item (index) BulkShardRequest [[workflow][2]] containing [index {[workflow][workflow_log][29ad0d4a-7e46-11e8-90cd-fa163e8e92af], source[n/a, actual length: [84.9kb], max length: 2kb]}]
java.lang.IllegalArgumentException: Limit of total fields [1000] in index [workflow] has been exceeded
	at org.elasticsearch.index.mapper.MapperService.checkTotalFieldsLimit(MapperService.java:626) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:450) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:353) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:285) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:313) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) ~[elasticsearch-6.2.2.jar:6.2.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by inutano** [comment]
Hi, thank you for trying! I might need to change the elasticsearch configuration to accept a huge json data, let me check the current setting

**Comment by kmhernan** [comment]
Yeah I was reading more and realized it’s something that needs to be handled with ELK. I haven’t figured out how to change that setting in particular though.

**Comment by inutano** [comment]
i guess the setting can be changed via ES api like this (https://discuss.elastic.co/t/total-fields-limit-setting/53004/2), or I may have to change the function to capture the workflow metadata so that it won't be too huge

**Comment by kmhernan** [comment]
Yeah we can try the PUT request as a quick workaround. Would like to find a better solution ultimately. When I get time today I’ll test and report back.

**Comment by kmhernan** [comment]
Ok @inutano I tested increasing the limit and it worked. Would still like to find a way to do this within the docker compose or something in the future

**Comment by inutano** [comment]
Thanks! It shoud be done during the index creation step invoked during the docker-compose up, where I run a container to exec a shell script.
https://github.com/inutano/docker-metrics-collector/blob/master/run-dmc/index_mapping_workflow.sh

I will put that setting here later and will close this issue. Thanks!

**Comment by inutano** [comment]
[The updated docker-metrics-collector](https://github.com/inutano/docker-metrics-collector/commit/79eabbc944ed8eb1726f1900ed298cfef8e2d27b) will create workflow index with 5000 fields limit using [a new docker-compose setting](https://quay.io/repository/inutano/run-dmc/build/257afe18-d664-4dd6-91f8-3bc5d5945978). Update docker-metrics-collector by `cd $HOME/.cwlmetrics/repos/dmc && git pull origin master` and restart cwl-metrics will affect.

Let me know if 5000 is not enough, and also, please notify me if you had any problem or trouble on collecting runtime metrics with increased limit - though I assume increased number does not affect to the performance.
